export const typeRawToType: Record<string, string> = {
    String: 'string',
    VarName: 'string',
    EnemySearch: 'string',
    VarCondition: 'string',
    Image: 'string',
    EffectSelect: 'string',
    EnemyState: 'string',
    Reaction: 'string',
    EnemyType: 'string',
    Timer: 'string',
    QuestResetSelect: 'string',
    CallEvent: 'string',
    Maps: 'string',
    Person: 'string',
    Character: 'string',
    TraderSelect: 'string',
    QuestHub: 'string',
    Shop: 'string',
    Area: 'string',
    Landmarks: 'string',
    LoreEntrySelect: 'string',
    LoreSelect: 'string',
    EnemyActionRef: 'string',
    TrackerRef: 'string',
    EntityAnim: 'string',
    SoundT: 'string',
    TrophySelect: 'string',
    WalkAnimConfig: 'string | ig.ActorEntity.WalkAnims',
    AnimSheetRef: 'string | ig.AnimationSheet.Settings',
    EntityAnimArray: 'string[]',
    CollabLabelFilter: 'string[]',
    Marker: 'Nullable<string>',

    Number: 'number',
    Integer: 'number',
    NumberArray: 'number[]',
    AnimFrames: 'number[]',
    FlexibleTable: 'number[][]',

    Vec3: 'Vec3',
    Offset: 'Vec3',
    Vec2: 'Vec2',
    Face: 'Vec2',

    Boolean: 'boolean',

    NPC: 'ig.Event.GetEntity',
    Entity: 'ig.Event.GetEntity',
    Actor: 'ig.Event.GetEntity',

    StringExpression: 'ig.Event.StringExpression',
    NumberExpression: 'ig.Event.NumberExpression',
    BooleanExpression: 'ig.Event.BooleanExpression',
    Vec2Expression: 'ig.Event.Vec2Expression',
    Vec3Expression: 'ig.Event.Vec3Expression',
    NumberVary: 'ig.Event.NumberVary',

    LangLabel: 'ig.LangLabel.Data',
    Quest: 'sc.QuestModel.QuestId',
    TaskIndex: 'sc.QuestModel.QuestId',
    QuestNameSelect: 'sc.QuestModel.QuestId',
    DropSelect: 'ig.Database.DropKey',
    AttackInfo: 'sc.AttackInfo.AttackSettings',
    Effect: 'ig.EffectHandle.Settings',
    ProxyRef: 'sc.ProxyTools.PrepareSrcProxySetting',
    Item: 'sc.ItemID',
    Color: 'ig.RGBColorData | string',
    GuiState: 'ig.GuiHook.State',
    QuestLabelSelect: 'ig.EVENT_STEP.SOLVE_QUEST_CONDITION.QuestLabelSelect',
    QuestTaskList: 'sc.QuestTask.TaskSettings[]',
    QuestRewards: 'sc.Quest.Rewards',
    Object: 'ig.ACTION_STEP.SET_PLAYER_ACTION_BLOCK.BlockData',
    PersonExpression: 'sc.MessageModel.PersonConfig',
    ModalChoiceOptions: 'ig.EVENT_STEP.SHOW_MODAL_CHOICE.ModalChoiceOption[]',
    ChoiceOptions: 'sc.MessageModel.OptionConfig[]',
    CombatConditions: 'sc.CombatConditions.ConditionConfig[]',
    Action: 'ig.Action.Step[]',
    PoiFilter: 'sc.COMBAT_POI.Setting',
    Animation: 'ig.EffectHandle.Settings',
    RandomDistribution: 'ig.ACTION_STEP.SELECT_RANDOM.OptionConfig[]',
    EventSheetCall: 'ig.EVENT_STEP.CALL_EVENT_FROM_SHEET.EventSheetCall',
    TileSheet: 'ig.TileSheet.Data',
    GUI: 'ig.EVENT_STEP.ADD_GUI.GUI',
    GUIState: 'ig.EVENT_STEP.CHANGE_GUI_STATE',
    Shield: 'sc.CombatShield.Setting',
    CreditsTriggerSelect: 'ig.EVENT_STEP.WAIT_UNTIL_CREDIT_TRIGGER.CreditsTriggerSelect',
} as const
